
key = values
Admin_input=//input[@id='1002']

--Login
 
username=//input[@id='user-name']
password=//input[@id='password']
loginButton=//input[@id='login-button']

backpackButton=//button[@id='add-to-cart-sauce-labs-backpack']
bikeLightButton=//button[@id='add-to-cart-sauce-labs-bike-light']
boltTShirtButton=//button[@id='add-to-cart-sauce-labs-bolt-t-shirt']
<<<<<<< HEAD
fleeceJacketButton=//button[@id='add-to-cart-sauce-labs-fleece-jacket']
=======
>>>>>>> ec47c2aaeba1a5767d880766b880577af1fe2d66
