
key = values
Admin_input=//input[@id='1002']

--Login
 
username=//input[@id='user-name']
password=//input[@id='password']
loginButton=//input[@id='login-button']

backpackButton=//button[@id='add-to-cart-sauce-labs-backpack']
bikeLightButton=//button[@id='add-to-cart-sauce-labs-bike-light']
boltTShirtButton=//button[@id='add-to-cart-sauce-labs-bolt-t-shirt']
